# Generated by Django 5.2.5 on 2025-08-11 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PizzaModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=120)),
                ('price', models.FloatField()),
                ('size', models.IntegerField()),
            ],
            options={
                'db_table': 'pizza_table',
            },
        ),
    ]
