# Generated by Django 5.2.5 on 2025-08-13 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizza', '0002_pizzamodel_pizza_shop'),
    ]

    operations = [
        migrations.AddField(
            model_name='pizzamodel',
            name='day',
            field=models.CharField(choices=[('MONDAY', 'Monday'), ('TUESDAY', 'Tuesday'), ('WEDNESDAY', 'Wednesday'), ('THURSDAY', 'Thursday'), ('FRIDAY', 'Friday'), ('SATURDAY', 'Saturday'), ('SUNDAY', 'Sunday')], default='tuesday', max_length=10),
            preserve_default=False,
        ),
    ]
