# Generated by Django 5.2.5 on 2025-08-14 14:38

import core.services.file_services
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizza', '0005_pizzamodel_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pizzamodel',
            name='photo',
            field=models.ImageField(blank=True, upload_to=core.services.file_services.upload_pizza_photo),
        ),
    ]
