# Generated by Django 5.2.5 on 2025-08-11 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fruits', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newfruitmodel',
            name='taste',
        ),
        migrations.AddField(
            model_name='newfruitmodel',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
